name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a my-first-hello-heroku
          heroku plugins:install @heroku-cli/plugin-java
          heroku deploy:jar build/libs/*.jar --jdk=17 --includes=src/main/resources/application.properties

