name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Install AWS CLI and Elastic Beanstalk CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

          pip3 install --user awsebcli

      - name: Prepare AWS Credentials Directory
        run: mkdir -p ~/.aws

      - name: Configure AWS Credentials
        run: |
          echo "[default]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          chmod 600 ~/.aws/credentials
      - name: Use environment variables
        run: |
          echo ${{ env.AWS_REGION }}
          echo ${{ env.AWS_ELASTIC_BEANSTALK_ENV_NAME }}

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          eb init -r ap-south-1 -p Corretto 17
          eb deploy User-management-env
